version: '3.7'

networks:
  bss:
  smd:

services:
  postgres-bss:
    hostname: postgres-bss
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=bssuser
      - POSTGRES_USER=bssuser
      - POSTGRES_DB=bssdb
    ports:
      - '5432:5432'
    networks:
      - bss
  postgres-smd:
    hostname: postgres-smd
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=hmsdsuser
      - POSTGRES_USER=hmsdsuser
      - POSTGRES_DB=hmsds
    ports:
      - '5433:5432'
    networks:
      - smd
  smd-init:
    hostname: smd-init
    image: ghcr.io/openchami/smd:v2.13.5
    environment:
      - SMD_DBHOST=postgres-smd
      - SMD_DBPORT=5432
      - SMD_DBUSER=hmsdsuser
      - SMD_DBPASS=hmsdsuser
      - SMD_DBNAME=hmsds
      - SMD_DBOPTS=sslmode=disable
    depends_on:
      - postgres-smd
    networks:
      - smd
    command: ["/smd-init"]
  smd:
    hostname: smd
    image: ghcr.io/openchami/smd:v2.13.5
    environment:
      - SMD_DBHOST=postgres-smd
      - SMD_DBPORT=5432
      - SMD_DBUSER=hmsdsuser
      - SMD_DBPASS=hmsdsuser
      - SMD_DBNAME=hmsds
      - SMD_DBOPTS=sslmode=disable
    depends_on:
      - postgres-smd
      - smd-init
    ports:
      - '27779:27779'
    networks:
      - bss
      - smd
  bss:
    hostname: bss
    environment:
      - BSS_USESQL=true
      - BSS_INSECURE=true
      - BSS_DBHOST=postgres-bss
      - BSS_DBPORT=5432
      - BSS_DBNAME=bssdb
      - BSS_DBUSER=bssuser
      - BSS_DBPASS=bssuser
    ports:
      - '27778:27778'
    build:
      context: .
    depends_on:
      - postgres-bss
      - smd
    networks:
      - bss
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:27778/boot/v1"]
      interval: 30s
      timeout: 10s
      retries: 5
  bss-test:
    hostname: bss-test
    build:
      context: .
      dockerfile: Dockerfile.bss-postgres-test.Dockerfile
    depends_on:
      bss:
        condition: service_healthy
        restart: true
    networks:
      - bss
