version: '3.7'

networks:
  bss:
  smd:

services:
  postgres:
    hostname: postgres
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=ochamiuser
      - POSTGRES_USER=ochamiuser
      - POSTGRES_MULTIPLE_DATABASES=hmsds,bssdb
    volumes:
      - ./scripts/pg-init:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    networks:
      - bss
      - smd
  smd-init:
    hostname: smd-init
    image: ghcr.io/openchami/smd:v2.13.5
    environment:
      - SMD_DBHOST=postgres
      - SMD_DBPORT=5432
      - SMD_DBUSER=ochamiuser
      - SMD_DBPASS=ochamiuser
      - SMD_DBNAME=hmsds
      - SMD_DBOPTS=sslmode=disable
    depends_on:
      - postgres
    networks:
      - smd
    command: ["/smd-init"]
  smd:
    hostname: smd
    image: ghcr.io/openchami/smd:v2.13.5
    environment:
      - SMD_DBHOST=postgres
      - SMD_DBPORT=5432
      - SMD_DBUSER=ochamiuser
      - SMD_DBPASS=ochamiuser
      - SMD_DBNAME=hmsds
      - SMD_DBOPTS=sslmode=disable
    depends_on:
      - postgres
      - smd-init
    ports:
      - '27779:27779'
    networks:
      - bss
      - smd
  bss-init:
    hostname: bss-init
    container_name: bss-init
    build:
      context: .
    environment:
      - BSS_POSTGRES=true
      - BSS_INSECURE=true
      - BSS_DBHOST=postgres
      - BSS_DBPORT=5432
      - BSS_DBNAME=bssdb
      - BSS_DBUSER=ochamiuser
      - BSS_DBPASS=ochamiuser
    depends_on:
      - postgres
    networks:
      - bss
    entrypoint:
      - /usr/local/bin/bss-init
  bss:
    hostname: bss
    environment:
      - BSS_USESQL=true
      - BSS_INSECURE=true
      - BSS_DBHOST=postgres
      - BSS_DBPORT=5432
      - BSS_DBNAME=bssdb
      - BSS_DBUSER=ochamiuser
      - BSS_DBPASS=ochamiuser
    ports:
      - '27778:27778'
    build:
      context: .
    depends_on:
      - postgres
      - bss-init
      - smd
    networks:
      - bss
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:27778/boot/v1"]
      interval: 30s
      timeout: 10s
      retries: 5
  bss-test:
    hostname: bss-test
    build:
      context: .
      dockerfile: Dockerfile.bss-postgres-test.Dockerfile
    depends_on:
      bss:
        condition: service_healthy
        restart: true
    networks:
      - bss
