name: Run CT Tests
on: [push, pull_request, workflow_dispatch]
jobs:
  run_ct_test:
    name: Run CT Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Checkout hms-simulation-environment
        uses: actions/checkout@v2
        with:
          # TODO check out a "stable" or "v1" tag, or somehow have it match the pointed branch that this workflow was referenced from
          fetch-depth: 0
          path: hms-simulation-environment
          repository: Cray-HPE/hms-simulation-environment

      - name: Build images under test
        shell: bash
        run: |
          # create service image
          make image

          # Update the docker-compose
          export IMAGE="cray-bss:$(cat .version)"
          yq -i e  '.services.cray-bss.image = env(IMAGE)' ./hms-simulation-environment/docker-compose.yaml

          # For debugging output the modified docker-compose compose file
          echo "Updated ./hms-simulation-environment/docker-compose.yaml"
          cat ./hms-simulation-environment/docker-compose.yaml

      - name: Standup simulation environment
        shell: bash
        run: |
          set -ex
          cd hms-simulation-environment

          # Setup python virtual environment
          ./setup_venv.sh
          . ./venv/bin/activate
          ./run.py configs/sls/small_mountain.json

      - name: Run smoke tests
        run: ./runSmokeTestsWithSimulator.sh

      - name: Load simulation for tavern tests
        run: ./runTavernTestsLoadSimulator.sh
      
      - name: Run tavern tests
        run: ./runTavernTestsWithSimulator.sh