    name: Run Unit Tests
    on: [push, pull_request]
    
    jobs:
      build:
        defaults:
          run:
            working-directory: ./cmd
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v4
          - name: Setup Go
            uses: actions/setup-go@v4
            with:
              go-version: '1.21.x'
          - name: Install dependencies
            run: go get ./boot-script-service ./bss-init
          - name: Generate .version
            run: make version
          - name: Test with the Go CLI
            run: go test ./boot-script-service ./bss-init
