    name: Run Unit Tests
    on: [push, pull_request]
    
    jobs:
      build:
        defaults:
          run:
            working-directory: ./cmd
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              fetch-tags: 1
              fetch-depth: 1

          - name: Set up latest stable Go
            uses: actions/setup-go@v5
            with:
              go-version: stable
          
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3

          - name: Install dependencies
            run: go get ./boot-script-service ./bss-init

          - name: Test with the Go CLI
            run: go test ./boot-script-service ./bss-init

          # Set environment variables required by GoReleaser
          - name: Set build environment variables
            run: |
              echo "GIT_STATE=$(if git diff-index --quiet HEAD --; then echo 'clean'; else echo 'dirty'; fi)" >> $GITHUB_ENV
              echo "BUILD_HOST=$(hostname)" >> $GITHUB_ENV
              echo "GO_VERSION=$(go version | awk '{print $3}')" >> $GITHUB_ENV
              echo "BUILD_USER=$(whoami)" >> $GITHUB_ENV
              echo "CGO_ENABLED=1" >> $GITHUB_ENV

          - name: Build with goreleaser
            uses: goreleaser/goreleaser-action@v6
            with:
              version: '~> v2'
              args: build --clean --snapshot
            id: goreleaser

          
